
# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      SECRET: ${{ vars.API_SCALEAWAY}}
      ACCES_KEY: ${{ vars.ACCES_KEY}}
      ORGANIZATION_ID: ${{ vars.ORGANIZATION_ID}}
      SECRET_KEY: ${{ vars.SECRET_KEY}}

    # steps to perform in job
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        working-directory: ./API
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
  
      - name: Login to Scaleway
        run : docker login rg.fr-par.scw.cloud/ynov-devops-container-registry -u nologin --password $SECRET
      
      - name: Create a new instance
        uses: jawher/action-scw@v2.6.2
        env:
          SCW_ACCESS_KEY:  ${{ vars.ACCES_KEY}}
          SCW_SECRET_KEY: ${{ vars.ORGANIZATION_ID}}
          SCW_ORGANIZATION_ID:   ${{ vars.SECRET_KEY}}
          SCW_DEFAULT_PROJECT_ID: 3cc6dc57-a36a-4e5a-9221-38e6b3cd9b01
          SCW_ZONE: fr-par-1
        with:
          args: instance server create image=ubuntu_bionic type=DEV1-S name=workhorse tags.0=temp tags.1=workhorse --wait -o=json

      - name: Get instance id and expose it in INSTANCE_ID env var
        run: echo ::set-env name=INSTANCE_ID::$(cat "${GITHUB_WORKSPACE}/scw.output" | jq -r '.id')

      - name: Do something with the instance
        run: ...

     
