name: Workflow-github-action
on:
  push:
    branches: [ release ]
    
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: release
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name : Dependencies Installation
        run: npm ci
        working-directory: API
      - name : Jest test
        run: npm test
        working-directory: API
      - name: Merge release into main 
        run: |
            git config --global user.name "Deolinas"
            git config --global user.email "lopezetienne@wanadoo.fr"
            git fetch --unshallow
            git checkout destroy
            git pull
            git merge --no-ff release -m "Merge release into main"
            git push

            


      
