name: Workflow-github-action
on:
  push:
    branches: [ release ]
    
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SECRET: ${{ vars.API_SCALEAWAY}}
      ACCES_KEY: ${{ vars.ACCES_KEY}}
      ORGANIZATION_ID: ${{ vars.ORGANIZATION_ID}}
      SECRET_KEY: ${{ vars.SECRET_KEY}}
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: release
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name : Dependencies Installation
        run: npm ci
        working-directory: API
      - name : Jest test
        run: npm test
        working-directory: API
      - name: Merge release into main 
        run: |
            git config --global user.name "Deolinas"
            git config --global user.email "lopezetienne@wanadoo.fr"
            git fetch --unshallow
            git checkout main
            git pull
            git merge --no-ff release -m "Merge release into main"
            git push

      - uses: actions/checkout@v2
      - name: Build the Docker image
        working-directory: ./API
        run: docker build . --file Dockerfile -t secretsanta
  
      - name: Login to Scaleway
        run : docker login rg.fr-par.scw.cloud/ynov-devops-container-registry -u nologin --password $SECRET
        
      - name : set image
        run : docker tag secretsanta:latest rg.fr-par.scw.cloud/ynov-devops-container-registry/secretsanta:latest
      
      - name : push image
        run : docker push rg.fr-par.scw.cloud/ynov-devops-container-registry/secretsanta:latest
      
      
      - name: Create a new instance
        uses: jawher/action-scw@v2.6.2
        env:
          SCW_ACCESS_KEY:  ${{ vars.ACCES_KEY}}
          SCW_SECRET_KEY: ${{ vars.ORGANIZATION_ID}}
          SCW_ORGANIZATION_ID:   ${{ vars.SECRET_KEY}}
          SCW_DEFAULT_PROJECT_ID: 3cc6dc57-a36a-4e5a-9221-38e6b3cd9b01
          SCW_ZONE: fr-par-1
        with:
          args: instance server create image=ubuntu_bionic type=DEV1-S name=workflow_release tags.0=temp tags.1=secretsanta_workflow --wait -o=json
